# Generated by Django 5.2.7 on 2025-12-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_journal_api', '0002_element_value_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to='tarot_journal_api.element'),
        ),
        migrations.AlterField(
            model_name='card',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to='tarot_journal_api.value'),
        ),
    ]
