# Generated by Django 5.2.7 on 2025-12-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_journal_api', '0003_alter_card_element_alter_card_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
