# Generated by Django 5.2.7 on 2025-12-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_journal_api', '0006_alter_spread_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tarot_journal_api.card')),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tarot_journal_api.spread')),
            ],
        ),
    ]
