# Generated by Django 5.2.7 on 2025-12-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_journal_api', '0007_spreadcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarot_journal_api.card'),
        ),
        migrations.AlterField(
            model_name='spreadcard',
            name='spread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot_journal_api.spread'),
        ),
    ]
