# Generated by Django 5.2.7 on 2025-12-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_journal_api', '0008_alter_spreadcard_card_alter_spreadcard_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='spread',
            name='title',
            field=models.CharField(default='Untitled Spread', max_length=200),
        ),
    ]
