# Generated by Django 5.2.7 on 2025-12-22 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_journal_api', '0010_alter_spread_user_alter_spreadcard_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadcard',
            name='spread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spread_cards', to='tarot_journal_api.spread'),
        ),
    ]
