# Generated by Django 6.0 on 2026-01-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_journal_api', '0011_alter_spreadcard_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.CharField(null=True),
        ),
    ]
